package report

import (
	"fmt"
	"html"
	"strings"
)

// HTML renders the report as a self-contained dark-themed HTML document with
// inline CSS (no external assets), so it can be opened or emailed as-is.
func (r Report) HTML() string {
	s, findings := summarize(r.Rows)
	var b strings.Builder

	b.WriteString("<!doctype html>\n<html lang=\"en\">\n<head>\n")
	b.WriteString("<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&b, "<title>ndscan report — %s</title>\n", esc(r.Generated))
	b.WriteString("<style>" + css + "</style>\n</head>\n<body>\n")

	fmt.Fprintf(&b, "<h1>Network scan <span class=\"muted\">%s</span></h1>\n", esc(r.Generated))

	b.WriteString("<div class=\"meta\">")
	if r.Targets != "" {
		fmt.Fprintf(&b, "<span><b>Targets</b> <code>%s</code></span>", esc(r.Targets))
	}
	if r.Preset != "" {
		fmt.Fprintf(&b, "<span><b>Preset</b> %s</span>", esc(r.Preset))
	}
	fmt.Fprintf(&b, "<span><b>%d</b> up</span><span><b>%d</b> ports</span><span><b>%d</b> flagged</span>",
		s.hostsUp, s.openPorts, s.flagged)
	b.WriteString("</div>\n")

	// Exposure.
	if len(findings) > 0 {
		fmt.Fprintf(&b, "<h2>⚠ Exposure <span class=\"muted\">%d high · %d warn</span></h2>\n", s.highCount, s.warnCount)
		b.WriteString("<table>\n<tr><th>Severity</th><th>Host</th><th>Port</th><th>Service</th><th>Reason</th></tr>\n")
		for _, f := range findings {
			host := esc(f.IP)
			if f.Host != "" {
				host = fmt.Sprintf("%s <span class=\"muted\">(%s)</span>", esc(f.IP), esc(f.Host))
			}
			fmt.Fprintf(&b, "<tr><td>%s</td><td>%s</td><td>%d</td><td>%s</td><td>%s</td></tr>\n",
				sevBadge(f.Severity), host, f.Port, esc(dash(f.Service)), esc(dash(f.Reason)))
		}
		b.WriteString("</table>\n")
	} else {
		b.WriteString("<h2 class=\"ok\">✓ Exposure</h2>\n<p class=\"muted\">No risky ports detected.</p>\n")
	}

	// Hosts.
	b.WriteString("<h2>Hosts</h2>\n")
	b.WriteString("<table>\n<tr><th>IP</th><th>Host</th><th>MAC</th><th>Vendor</th><th>OS</th><th>RTT</th><th>Open ports</th></tr>\n")
	for _, row := range r.Rows {
		os := esc(dash(row.OS))
		if row.OS != "" && row.OSAccuracy > 0 {
			os = fmt.Sprintf("%s <span class=\"muted\">(%d%%)</span>", esc(row.OS), row.OSAccuracy)
		}
		fmt.Fprintf(&b, "<tr><td><code>%s</code></td><td>%s</td><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
			esc(row.IP), esc(dash(row.Host)), esc(dash(row.MAC)), esc(dash(row.Vendor)),
			os, esc(dash(row.RTT)), esc(portSummary(row)))
	}
	b.WriteString("</table>\n")

	// Service detail.
	detailed := false
	for _, row := range r.Rows {
		if len(row.PortDetails) == 0 {
			continue
		}
		if !detailed {
			b.WriteString("<h2>Service detail</h2>\n")
			detailed = true
		}
		head := esc(row.IP)
		if row.Host != "" {
			head = fmt.Sprintf("%s <span class=\"muted\">(%s)</span>", esc(row.IP), esc(row.Host))
		}
		fmt.Fprintf(&b, "<h3>%s</h3>\n<ul class=\"svc\">\n", head)
		for _, p := range row.PortDetails {
			lock := ""
			if p.TLS {
				lock = " <span class=\"tls\">🔒 TLS</span>"
			}
			ver := ""
			if vl := p.VersionLabel(); vl != "" {
				ver = " — " + esc(vl)
			}
			fmt.Fprintf(&b, "<li><b>%d/%s</b> %s%s%s\n", p.Port, esc(p.Proto), esc(p.Service), lock, ver)
			b.WriteString("<ul>\n")
			sub := func(k, v string) {
				if v != "" {
					fmt.Fprintf(&b, "<li><span class=\"muted\">%s:</span> %s</li>\n", k, esc(v))
				}
			}
			sub("info", p.ExtraInfo)
			sub("title", p.HTTPTitle)
			sub("cert", p.Cert)
			sub("cpe", p.CPE)
			if p.Risk != "" {
				fmt.Fprintf(&b, "<li>%s %s</li>\n", sevBadge(p.Severity), esc(p.Risk))
			}
			b.WriteString("</ul>\n</li>\n")
		}
		b.WriteString("</ul>\n")
	}

	b.WriteString("<footer>Generated by ndscan.</footer>\n</body>\n</html>\n")
	return b.String()
}

func esc(s string) string { return html.EscapeString(s) }

func sevBadge(severity string) string {
	switch severity {
	case "high":
		return `<span class="sev high">HIGH</span>`
	case "warn":
		return `<span class="sev warn">WARN</span>`
	case "info":
		return `<span class="sev info">info</span>`
	default:
		return ""
	}
}

const css = `
:root{color-scheme:dark}
body{background:#0b1120;color:#e5e7eb;font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;padding:2rem;max-width:1000px;margin:0 auto}
h1{font-size:1.6rem;margin:0 0 1rem}
h2{font-size:1.2rem;border-bottom:1px solid #1f2937;padding-bottom:.3rem;margin-top:2rem}
h3{font-size:1rem;color:#22d3ee;margin:1.2rem 0 .4rem}
.muted{color:#6b7280;font-weight:400}
.ok{color:#34d399}
code{background:#111827;padding:.1rem .35rem;border-radius:4px;font-size:.85em}
.meta{display:flex;flex-wrap:wrap;gap:1.2rem;color:#9ca3af;margin-bottom:1rem}
.meta b{color:#e5e7eb}
table{border-collapse:collapse;width:100%;margin:.6rem 0;font-size:.9rem}
th,td{text-align:left;padding:.4rem .6rem;border-bottom:1px solid #1f2937;vertical-align:top}
th{color:#22d3ee;font-weight:600}
tr:hover td{background:#111827}
.sev{display:inline-block;padding:.05rem .4rem;border-radius:4px;font-size:.75rem;font-weight:700}
.sev.high{background:#7f1d1d;color:#fecaca}
.sev.warn{background:#78350f;color:#fde68a}
.sev.info{background:#155e75;color:#a5f3fc}
.tls{color:#34d399;font-size:.8rem}
ul.svc{list-style:none;padding-left:0}
ul.svc>li{margin:.4rem 0}
ul.svc ul{color:#9ca3af;margin:.2rem 0 .2rem 1rem}
footer{margin-top:2rem;padding-top:1rem;border-top:1px solid #1f2937;color:#6b7280;font-size:.85rem}
`
