package report

import (
	"fmt"
	"strings"
)

// mdEsc renders network-derived text safe for inline Markdown: line breaks
// would split a table row or list item apart, and backticks/brackets would
// inject formatting into reports people paste into GitHub.
func mdEsc(s string) string {
	return mdEscaper.Replace(s)
}

var mdEscaper = strings.NewReplacer(
	"\r\n", " ", "\r", " ", "\n", " ",
	"`", "\\`",
	"[", "\\[",
	"]", "\\]",
)

// mdCell is mdEsc plus pipe escaping — a raw | ends a table cell early and
// breaks the whole row.
func mdCell(s string) string {
	return strings.ReplaceAll(mdEsc(s), "|", "\\|")
}

// Markdown renders the report as a GitHub-flavored Markdown document.
func (r Report) Markdown() string {
	s, findings := summarize(r.Rows)
	var b strings.Builder

	fmt.Fprintf(&b, "# Network scan — %s\n\n", dash(r.Generated))

	// Metadata + headline stats.
	if r.Targets != "" {
		fmt.Fprintf(&b, "**Targets:** `%s`  \n", r.Targets)
	}
	if r.Preset != "" {
		fmt.Fprintf(&b, "**Preset:** %s  \n", r.Preset)
	}
	fmt.Fprintf(&b, "**Summary:** %d host(s) up · %d open port(s) · %d host(s) flagged\n\n",
		s.hostsUp, s.openPorts, s.flagged)

	// Exposure section: only when something was flagged.
	if len(findings) > 0 {
		b.WriteString("## ⚠ Exposure\n\n")
		fmt.Fprintf(&b, "%d high · %d warn\n\n", s.highCount, s.warnCount)
		b.WriteString("| Severity | Host | Port | Service | Reason |\n")
		b.WriteString("|----------|------|------|---------|--------|\n")
		for _, f := range findings {
			host := mdCell(f.IP)
			if f.Host != "" {
				host = fmt.Sprintf("%s (%s)", mdCell(f.IP), mdCell(f.Host))
			}
			fmt.Fprintf(&b, "| %s | %s | %d | %s | %s |\n",
				sevLabel(f.Severity), host, f.Port, mdCell(dash(f.Service)), mdCell(dash(f.Reason)))
		}
		b.WriteString("\n")
	} else {
		b.WriteString("## ✓ Exposure\n\nNo risky ports detected.\n\n")
	}

	// Host inventory table.
	b.WriteString("## Hosts\n\n")
	b.WriteString("| IP | Host | MAC | Vendor | OS | RTT | Open ports |\n")
	b.WriteString("|----|------|-----|--------|----|----|-----------|\n")
	for _, row := range r.Rows {
		os := mdCell(dash(row.OS))
		if row.OS != "" && row.OSAccuracy > 0 {
			os = fmt.Sprintf("%s (%d%%)", mdCell(row.OS), row.OSAccuracy)
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n",
			mdCell(row.IP), mdCell(dash(row.Host)), mdCell(dash(row.MAC)), mdCell(dash(row.Vendor)),
			os, mdCell(dash(row.RTT)), mdCell(portSummary(row)))
	}
	b.WriteString("\n")

	// Per-host service detail — only for hosts that actually have ports.
	detailed := false
	for _, row := range r.Rows {
		if len(row.PortDetails) == 0 {
			continue
		}
		if !detailed {
			b.WriteString("## Service detail\n\n")
			detailed = true
		}
		head := mdEsc(row.IP)
		if row.Host != "" {
			head += " (" + mdEsc(row.Host) + ")"
		}
		fmt.Fprintf(&b, "### %s\n\n", head)
		for _, p := range row.PortDetails {
			fmt.Fprintf(&b, "- **%d/%s** %s", p.Port, mdEsc(p.Proto), mdEsc(p.Service))
			if p.TLS {
				b.WriteString(" 🔒")
			}
			if vl := p.VersionLabel(); vl != "" {
				fmt.Fprintf(&b, " — %s", mdEsc(vl))
			}
			b.WriteString("\n")
			sub := func(k, v string) {
				if v != "" {
					fmt.Fprintf(&b, "  - %s: %s\n", k, mdEsc(v))
				}
			}
			sub("info", p.ExtraInfo)
			sub("title", p.HTTPTitle)
			sub("cert", p.Cert)
			sub("cpe", p.CPE)
			if p.Risk != "" {
				fmt.Fprintf(&b, "  - %s **%s**\n", sevLabel(p.Severity), mdEsc(p.Risk))
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n_Generated by ndscan._\n")
	return b.String()
}

// sevLabel renders a severity as a short Markdown-safe tag.
func sevLabel(severity string) string {
	switch severity {
	case "high":
		return "🔴 HIGH"
	case "warn":
		return "🟡 WARN"
	case "info":
		return "🔵 info"
	default:
		return ""
	}
}
